### ISSUE TITLE
Use of undeclared Var goog.log/warn

### ISSUE THREAD

**Issue by cloojure** [bhauman/figwheel-main#238] opened 2020-03-15 19:48 UTC
```pre
[Figwheel:WARNING] Compile Warning   target/public/cljs-out/tests/figwheel/repl.cljc   line:610  column:6

  Use of undeclared Var goog.log/warn

  605  (defn set-log-level [logger' level]
  606    (if-let [lvl (get log-levels level)]
  607      (do
  608        (.setLevel logger' lvl)
  609        (debug (str "setting log level to " level)))
  610      (glog/warn (str "Log level " (pr-str level) " doesn't exist must be one of "
            ^---
  611                      (pr-str '("severe" "warning" "info" "config" "fine" "finer" "finest"))))))
  612  
  613  (defn init-log-level! []
  614    (doseq [logger' (cond-> [logger]
  615                      (exists? js/figwheel.core)

[Figwheel] Successfully compiled build tests to "target/public/cljs-out/tests-main.js" in 17.169 seconds.
Launching Javascript environment with script:  "./chrome-headless.bash"
Environment output being logged to: target/public/cljs-out/tests/js-environment.log

Testing tst._bootstrap

----------------------------
   ClojureScript 1.10.597
----------------------------
```

-----------------------------------------------
Clojure version:  1.10.2-alpha1

**Comment by palfrey** [comment] 2020-05-03 21:50
Duplicate of #10 which should be fixed now

**Closed** 2022-04-30 19:51 UTC
