### ISSUE TITLE
Triggering a REPL open with --repl doesn't work in Firefox 62.0 on Ubuntu

### ISSUE THREAD

**Issue by teodorlu** [bhauman/figwheel-main#98] opened 2018-09-27 15:21 UTC
Hello!

When I launch figwheel with `clojure -m figwheel.main -b dev -r` in a project with `deps.edn`, `dev.cljs.edn` and some ClojureScript source, I get different behavior from Chromium and Firefox. In Chromium, the REPL shows up normally. In Firefox, I never see a REPL. Code compilation works, however, and the browser runs the code I write in source files.

- Is Firefox supported?
- Do you wish to persue this? It caused some head-scratching on my part, but I'm fine with Chromium. If so, I'd be happy to provide more information.

Console output when running with Firefox:

```
Installing CLJS DevTools 0.9.10 and enabling features :formatters :hints :async util.cljs:187:55
Feature :formatters cannot be installed. Unsupported Javascript context: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0. util.cljs:248:13
CLJS DevTools: some custom formatters were not rendered.
https://github.com/binaryage/cljs-devtools/blob/master/docs/faq.md#why-some-custom-formatters-were-not-rendered util.cljs:136:13
log:Opening the WebSocket on ws://localhost:9500/figwheel-connect?fwprocess=643e14&fwbuild=dev&fwsid=2f225b80-f9cc-44be-8caa-e194f2ab4623 logger.js:367:5
 [goog.net.WebSocket] Opening the WebSocket on ws://localhost:9500/figwheel-connect?fwprocess=643e14&fwbuild=dev&fwsid=2f225b80-f9cc-44be-8caa-e194f2ab4623 console.js:203:5
log:WebSocket opened on ws://localhost:9500/figwheel-connect?fwprocess=643e14&fwbuild=dev&fwsid=2f225b80-f9cc-44be-8caa-e194f2ab4623 logger.js:367:5
 [goog.net.WebSocket] WebSocket opened on ws://localhost:9500/figwheel-connect?fwprocess=643e14&fwbuild=dev&fwsid=2f225b80-f9cc-44be-8caa-e194f2ab4623 console.js:203:5
log:Session ID: 2f225b80-f9cc-44be-8caa-e194f2ab4623 logger.js:367:5
 [Figwheel REPL] Session ID: 2f225b80-f9cc-44be-8caa-e194f2ab4623 console.js:203:5
log:Session Name: Roselle logger.js:367:5
 [Figwheel REPL] Session Name: Roselle console.js:203:5 
```

Regards,
Teodor

**Comment by smahood** [comment] 2018-09-27 16:36
Can you get it to load in Firefox with just the basic REPL from the instructions at https://figwheel.org/docs/installation.html#dependencies-with-cli-tools ? How about if you try the build in https://figwheel.org/docs/create_a_build.html#start-a-build-with-cli-tools ?
As far as my experience goes, I'm able to load my REPL in Firefox without any issues for both the REPL and my builds, but I did run into problems with things working inconsistently while getting my builds going. If you run into issues with the configurations in the figwheel docs then I can try them on my machines and see if we can pinpoint where the issue occurs.

**Comment by teodorlu** [comment] 2018-09-28 08:16
Hello @smahood,

As far as I can tell, there aren't any differences between the guide and my setup.

My setup: https://github.com/teodorlu/figwheel-main-issue-98-reproduction

**Comment by bhauman** [comment] 2018-09-28 13:30
OK, you have to click the alert! because that is a blocking the process. Or
simply replace the alert with a console.log

**Comment by teodorlu** [comment] 2018-10-01 12:40
Yeah, alert blocks the REPL from appearing in any browser. Here's what I see after running `clojure -m figwheel.main -b dev -r` and clicking the alert away:

![2018-10-01-143828_1722x707_scrot](https://user-images.githubusercontent.com/5285452/46288988-eb13cb80-c587-11e8-9e4d-5f9f6cf0c5b2.png)

**Comment by bhauman** [comment] 2018-10-01 13:13
I’m not entirely sure what’s happening. 

I’d first get rid of the alert. I’d also remove the rebel readline library just in case you are running it in an incompatible environment.

**Comment by bhauman** [comment] 2018-10-01 16:19
@teodorlu when I look at the photo of your terminal it looks like there is a rendering problem as there is a line that is drawn through the previous line of text. Are you using a standard piece of terminal software?

I'm at a loss because this of course works on my system and many others.  It sounds like something very basic is amiss here. If you can change files and they get reloaded, then I'd say this is a problem with your terminal where it isn't echoing a prompt. Or that you need to reload the browser window because there is some strange race condition.

Or if when you change a file it doesn't reload and you get no feedback from the browser, then I'd say its a network connection problem and somehow the websocket connection is failing.

**Comment by teodorlu** [comment] 2018-10-02 08:29
Not quite standard, I guess. What you saw above was Gnome Terminal on i3 (Window manager), running Zsh.

I get the same behavior on a default Ubuntu setup, with Gnome Terminal and Bash.

![2018-10-02-101804_1598x847_scrot](https://user-images.githubusercontent.com/5285452/46337324-90cd4600-c62d-11e8-86cb-244097a847bb.png)

It doesn't seem to me that we'll get a fix for this from eyeballing. I'm not sufficiently familiar with Figwheel-main to try debugging from the source. Should we leave this as-is, and come back to it if we get any better ideas?

**Comment by teodorlu** [comment] 2018-10-02 08:32
A last data-point. I get the same behavior when I try to launch a CLJS REPL from within CIDER.

1. Run `cider-jack-in-cljs`
2. Choose `figwheel-main`
3. Select `:dev`

Opening `localhost:9500` in Chrome/Chromium triggers a REPL to load. In Firefox, no luck.

**Comment by seanpoulter** [comment] 2019-07-18 01:14
Is this still happening @teodorlu? If it is, I've got a hunch. The REPL connects when the `load` event fires. If it `load` event has already fired, then nothing happens. I've run into this problem today and @bhauman has already merged in a fix (bhauman/figwheel-repl#6).

To check if that's what's happening for you, we can modify one of the compiled JavaScript files to tell us if the load event has fired:

**:output-dir/figwheel/repl/preload.js**
```diff
// Compiled by ClojureScript 1.10.520 {}
goog.provide('figwheel.repl.preload');
goog.require('cljs.core');
goog.require('figwheel.repl');
+ console.log(`document.readystate is "${document.readystate}".`);
if(cljs.core._EQ_.call(null,figwheel.repl.host_env,new cljs.core.Keyword(null,"html","html",-998796897))){
goog.global.addEventListener("load",(function (){
return figwheel.repl.connect.call(null);
}));
} else {
figwheel.repl.connect.call(null);
}

//# sourceMappingURL=preload.js.map
```

If you open up the usual page where you'd expect the REPL to connect, go and check the console. If you see that the `document.readystate` is `complete` then the `load` event had already fired and the REPL will never connect. Hopefully that's the cause.🤞 

Let me know if any of that didn't make sense, and let us know what the outcome is!

**Comment by teodorlu** [comment] 2019-07-18 13:58
Hello, @seanpoulter!

Thanks for looking into this. I'm currently enjoying some time off in the Norwegian mountains, but I will definitely see if this is the help that I've been needing when I get back to the city!

Teodor

**Comment by teodorlu** [comment] 2019-07-22 11:23
Hi again, @seanpoulter,

I can no longer reproduce the issue. I'm using the exact same reproduction repo, without any updated dependencies. Firefox version is updated to 68.0 from 62.0.

As I no longer have the issue, I'm inclined to close this, unless we really want to dig deeper. Sounds good?

Thanks again,
Teodor

**Closed** 2022-04-30 19:31 UTC
